config/routes.rb
Rails.application.routes.draw do
 
  resources :folders
  resources :documents
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'
  
  

  root                'statics_pages#home'
  get    'help'    => 'statics_pages#help'
  get    'about'   => 'statics_pages#about'
  get    'contact' => 'statics_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'folders/:folder_id' => 'folders#browse'
  get    'folders/:folder_id/new' => 'folders#new', :as => 'new_sub_folder' 
  get    'folders/:folder_id/new_document' => 'documents#new', :as => 'new_sub_document'
  
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/folder.rb
class Folder < ActiveRecord::Base
    acts_as_tree
    belongs_to :user
    has_many :documents
    
    def initialize(params = {})
    folder = params.delete(:folder)
    super
    if folder
      self.name = sanitize_filename(folder.original_name)
      self.parent_id = folder.parent_id
      self.user_id = folder.user_id
    end
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
   

  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.roots
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = Folder.find(params[:id])
    @folders = @folder.children
    @current_folder= Folder.find(params[:id])
    @documents = Document.where("folder_id is id")
  end

  # GET /folders/new
  def new
    @folder = Folder.new
    if params[:folder_id]
      @current_folder = Folder.find(params[:folder_id])
      @folder.parent_id = @current_folder.id
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    if @folder.save
       flash[:notice] = "Folder was successfully created."
        #format.json { render :show, status: :created, location: @folder }
        
        if @folder.parent
          redirect_to folder_path(@folder.parent_id)
        else
          redirect_to @folder
        end
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
    end
  end 

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    @folder = current_user.folders.find(params[:id])
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder = Folder.find(params[:id])
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def browse
    @current_folder = Folder.find(params[:folder_id])
    
    if @current_folder
      
      @folders = @current_folder.children
      
      @documents = @current_folder.all
      
      render :action => "index"
      
    else
      flash[:error] = "Folder does not exist"
      redirect_to root_url 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name, :parent_id, :user_id)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.collection_select :user_id, User.all, :id, :name %> <br>
  </div>
  
  <div class="field">
    <%= f.collection_select :parent_id, Folder.all, :id, :name %> <br>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.parent_id %></td>
        <td><%= folder.user_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %><br>
</p>

<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %><br>
</p>

<p>
  <strong>User:</strong>
  <%= @folder.user_id %><br>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>


<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.parent_id %></td>
        <td><%= folder.user_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <% @documents.each do |document| %>
      <tr>
        <td><%= document.filename %></td>
        <td><%= document.content_type %></td>
        <td>Owner: <%= document.belongs_to %> </td>
        <td><%= link_to 'Download', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%= link_to 'New Document', new_sub_document_path(@current_folder) %>

<%= link_to 'New Folder', new_sub_folder_path(@current_folder) %>